### ISSUE TITLE
Provide hooks for embedded images

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-richtext-behavior#10]
We need to interact with injected images, either by making them top-level nodes (slotted styling) or injecting stylesheets.

Few things:

- All images should have cursor:pointer when article is editable
- Images should auto-focus when embeded
- When focussed, images should have (our own) blue outline (ie: have a focussed attr/class)
- Images should have attrs/classes for what position they have, so devs can hook in (eg: custom offsets, medium-style width overflows if positioned center, etc)

A lot of this will be the same for other configurable embeds - eg: OEmbed/videos/etc

**Comment by bedeoverend** [comment]
So my local branch has fixed images so they're now top-level nodes, therefore they can be styled through `::slotted`. Which resolves most of these issues.

> All images should have cursor:pointer when article is editable

Should be fixed via styling on element.

> Images should auto-focus when embeded

Working on this, will be mainline soon. _Edit: Fixed. (I believe in 3f73355b9d15397baae9a0c7e4a78bf526f2df45 though not sure, but can no longer replicate)_

> When focussed, images should have (our own) blue outline (ie: have a focussed attr/class)

Should be fixed via styling on element.

> Images should have attrs/classes for what position they have, so devs can hook in (eg: custom offsets, medium-style width overflows if positioned center, etc)

After discussion IRL this will be on the `data-alignment` property. _Edit: Fixed in 944d2a2d223fc2b3d0b67fae69ebea1b1d2cba20_

**Comment by bedeoverend** [comment]
Closing this, as relevant remaining tasks should be left to the element using RichText.
