### ISSUE TITLE
Make subprops notify?

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-richtext-behavior#8]
Not sure if this is possible to do in a general way, but would be nice to be able to declaratively bind to subprops on the returned instance, rather than having to programatically setup listeners using the inbuilt emitter.

Eg:

```html
<button
    class="range__tool"
    data-format="bold"
    active$="[[editor.plugins.bold.applied]]">
    ...
</button>
```

**Comment by bedeoverend** [comment]
So given this isn't a Polymer Behavior, just pure JS class, this'd have to be some code you add to something like simpla-article. It'd look something like:

```js
editor.on('plugin', plugin => {
  Object.keys(plugin).forEach(prop => {
    this.notifyPath(`editor.plugins.${plugin.name}.${prop}`);
  });
});
```

that's potentially a little wasteful, as not every prop will have changed, but I'd say it's a minor point given how small the plugin state is.

Also yeah given this is Polymer specific behavior, so I'd say implement manually on simpla-article, and if it becomes a really common chore, we can turn this into a Polymer behavior? We can also have a couple of different exports in this package - a Polymer Behavior + Vanilla Class.

**Comment by bedeoverend** [comment]
Just realised I probably was just saying - "nah do what you said you didn't want to do"...but yeah could export a real Polymer Behavior. Or are you talking more about being able to do something like `editor.observe('plugins.bold.applied', (applied) => this.set('plugin.bold.applied', applied))`? Probably not worth the effort of setting something like that up I'd say

Also just realised that `notifyPath` would then break down on `meta` (or any sub-subproperty) because `notifyPath` only notifies of that exact path, not of child paths. So calling `notifyPath('plugins.heading.meta')` won't trigger a change if the binding is e.g. `notifyPath('plugins.heading.meta.level')`.

**Comment by madeleineostoja** [comment]
Alrighty, no worries
